micronaut:
  application:
    name: mncache
  caches:
    sample:
      charset: UTF-8
    suspended:
      charset: UTF-8
    suspended2:
      charset: UTF-8
netty:
  default:
    allocator:
      max-order: 3
